#!/bin/bash

set -eux

export NODE_ENV=dev

if [[ "$@" =~ "jvm" ]]; then
    clojure -Srepro -A:dev -m cljs.main -re node -co dev.cljs.edn -c my-ns.logging -r
else
    clojure -Srepro -A:dev:rebel -m figwheel.main -b dev -r
fi
